name: Lint and Test Charts

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@main
        with:
          command: lint
          config: ct.yaml
      - name: Run unitest
        run: |
          cd test
          go test
